### ISSUE TITLE
Install pytorch-gpu makes errors

### ISSUE THREAD

**Issue by partrita** [prefix-dev/pixi#1231]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```pixi.toml
[project]
name = "learn_transformers"
version = "0.1.0"
description = "Add a short description here"
authors = ["fkt <deepthought@postech.ac.kr>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.10.*"
pytorch-gpu = ">=1.11.0,<1.12"
```

```shell
>pixi run python
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fkt/Downloads/learn_transformers/.pixi/envs/default/lib/python3.10/site-packages/torch/__init__.py", line 198, in <module>
    _load_global_deps()
  File "/home/fkt/Downloads/learn_transformers/.pixi/envs/default/lib/python3.10/site-packages/torch/__init__.py", line 151, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/fkt/Downloads/learn_transformers/.pixi/envs/default/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/fkt/Downloads/learn_transformers/.pixi/envs/default/lib/python3.10/site-packages/torch/lib/../../../../libcublas.so.11: undefined symbol: free_gemm_select, version libcublasLt.so.11
>>> exit()
```

```bash
❯ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0

❯ nvidia-smi
Fri Apr 19 09:51:49 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.171.04             Driver Version: 535.171.04   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        Off | 00000000:01:00.0 Off |                  Off |
|  0%   40C    P8              22W / 450W |    222MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2134      G   /usr/lib/xorg/Xorg                          132MiB |
|    0   N/A  N/A      2281      G   /usr/bin/gnome-shell                         17MiB |
|    0   N/A  N/A      4679      G   ...,262144 --variations-seed-version=1       58MiB |
+---------------------------------------------------------------------------------------+
```

### Issue description

I've tried to use `pixi` for install `pytorch-gpu` but it gives me a error msg. If I tried `pytorch` which is cpu only version. That just works fine. But that's not what i want.

### Expected behavior

```bash
>>> import torch
>>> torch.cuda.available()
True
```

**Comment by partrita** [comment]
I tried below command, and it works.

```bash
pixi add --pypi torch
```

**Comment by ruben-arts** [comment]
Currently you need to tell pixi you have cuda available.
 
```toml
[system-requirements]
cuda = "12"
```

This will take care of solving the correct packages. Currently you got some age old incorrectly configured package. Note the latest pytorch-gpu is 2.1.2.

**Comment by partrita** [comment]
> Currently you need to tell pixi you have cuda available.
> 
> ```toml
> [system-requirements]
> cuda = "12"
> ```
> 
> This will take care of solving the correct packages. Currently you got some age old incorrectly configured package. Note the latest pytorch-gpu is 2.1.2.

You're right. I works beautifully.

```toml
[project]
name = "hugging"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[system-requirements]
cuda = "12"

[tasks]

[dependencies]
python = "3.10.*"
pytorch-gpu = ">=2.1.2,<2.2"
```

No problem to install, and CUDA is available!

```shell
pixi run python
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
```

**Comment by ianzone** [comment]
what's the difference between `pytorch-gpu` and `pytorch-cuda`?

**Comment by ruben-arts** [comment]
@ianzone The structure on getting the right code on your machine differs between `pytorch` and `conda-forge` which makes these two package act similar but with different names.
