### ISSUE TITLE
Provide feedback when local install editable fails

### ISSUE THREAD

**Issue by mickvangelderen** [prefix-dev/pixi#1439]
### Problem description

I have a Dockerfile that copies over the dependencies and lockfile before copying the source code in:

```Dockerfile
FROM ghcr.io/prefix-dev/pixi
WORKDIR /workspace
COPY pixi.lock pyproject.toml ./
RUN pixi install --locked --no-progress
ENV PATH="$PATH:/workspace/.pixi/envs/default/bin"
COPY . .
```

The pyproject.toml specifies:

```toml
[tool.pixi.pypi-dependencies]
application = { path = ".", editable = true }

[project.scripts]
example-job = "application.bin.example_job:main"
```

Running `docker run <container> example-job` fails with `ModuleNotFoundError`.

Making sure the `application/` folder exists before running `pixi install` for the first time solved this.

```Dockerfile
...
COPY pixi.lock pyproject.toml ./
RUN mkdir application # <== ADDED
RUN pixi install --locked --no-progress
...
```

From inside the container, running `pixi install` again after adding the `application/` folder does not solve the issue, deleting `.pixi` and reinstalling `pixi install` does:

```
root@0678781bb132:/workspace# example-job
Traceback (most recent call last):
  File "/workspace/.pixi/envs/default/bin/example-job", line 5, in <module>
    from application.bin.example_job import main
ModuleNotFoundError: No module named 'application'
root@0678781bb132:/workspace# pixi install
Project in /workspace is ready to use!
root@0678781bb132:/workspace# example-job
Traceback (most recent call last):
  File "/workspace/.pixi/envs/default/bin/example-job", line 5, in <module>
    from application.bin.example_job import main
ModuleNotFoundError: No module named 'application'
root@0678781bb132:/workspace# rm -rf .pixi
root@0678781bb132:/workspace# pixi install --locked --no-progress
Project in /workspace is ready to use!
root@0678781bb132:/workspace# example-job
Hello from test-job!
```

It would be nice to get a warning or error instead of silent failure. Perhaps `pixi install` after adding the folder should re-issue the local editable install.

**Comment by tdejager** [comment]
To clarify :) Is the `application` available as source in the docker?

**Comment by mickvangelderen** [comment]
> 1. To clarify :) Is the `application` available as source in the docker?

Not before running `pixi install`. This is what I meant to describe with "before copying in the source code" and what is shown in the first dockerfile. 

> 2. You are using the `setuptools` build backend or something else :)?

I suppose so, the pyproject.toml contains:

```
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
```

The `pyproject.toml` was written based on the advice in https://pixi.sh/latest/tutorials/python/.

**Comment by tdejager** [comment]
T.b.h I haven't really thought of the case were you do not have the source for an editable, we could do some checks beforehand. However, I can't do much once it gets in to the build step, as uv is handling this.

**Comment by mickvangelderen** [comment]
Within the context of docker images, copying over the dependency files first but not the source is fairly common to avoid redoing the installation of dependencies in the docker image every time the source code changes and a docker build is triggered.

I just wanted to report my user experience of using pixi with docker. I count on the maintainers to do what they think is right, whether that is to add some info to the pixi (docker) documentation, add a check in pixi, find a way to get uv to trigger a warning or error, or do nothing. Thanks for thinking about this and for the work on pixi in general!
