### ISSUE TITLE
Thread 'main' panicked at 'called `Option::unwrap()` on a `None` value' error on pixi init . on Windows

### ISSUE THREAD

**Issue by traversaro** [prefix-dev/pixi#154]
On my Windows machine, with pixi 0.0.5 `pixi init` or `pixi init .` fails with error:

~~~
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\cli\init.rs:52:32
~~~

While `pixi init ./otherdir` works fine. `pixi init .` was working fine with earlier versions of `pixi`, but I do not remember the exact version.

Extended log:

~~~
C:\src\onnx-benchmark>pixi init
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\cli\init.rs:52:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

C:\src\onnx-benchmark>pixi init -v
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\cli\init.rs:52:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

C:\src\onnx-benchmark>cd ..

C:\src>pixi init onnx-benchmark
✔ Initialized project in onnx-benchmark

C:\src>pixi --version
pixi 0.0.5
~~~

**Comment by traversaro** [comment]
Full backtrace:
~~~
C:\src\onnx-benchmark\test>pixi init .
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\cli\init.rs:52:32
stack backtrace:
   0:     0x7ff6d911a913 - <unknown>
   1:     0x7ff6d8a1b81b - <unknown>
   2:     0x7ff6d90fc1e1 - <unknown>
   3:     0x7ff6d911cdfb - <unknown>
   4:     0x7ff6d911c9d8 - <unknown>
   5:     0x7ff6d911d8f8 - <unknown>
   6:     0x7ff6d911d304 - <unknown>
   7:     0x7ff6d911d289 - <unknown>
   8:     0x7ff6d911d274 - <unknown>
   9:     0x7ff6d92a5a95 - <unknown>
  10:     0x7ff6d92a5b8c - <unknown>
  11:     0x7ff6d8d35b6b - <unknown>
  12:     0x7ff6d8c70aa7 - <unknown>
  13:     0x7ff6d8bae82f - <unknown>
  14:     0x7ff6d8ccf4c6 - <unknown>
  15:     0x7ff6d8bace0f - <unknown>
  16:     0x7ff6d9288ecc - <unknown>
  17:     0x7ffb296455a0 - BaseThreadInitThunk
  18:     0x7ffb2a7c485b - RtlUserThreadStart
~~~
