### ISSUE TITLE
PermissionDenied Error in PowerShell: A Puzzling Discrepancy

### ISSUE THREAD

**Issue by partrita** [prefix-dev/pixi#1754]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
[project]
name = "test_pixi"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge", "pytorch"]
platforms = ["win-64"]

[tasks]
start = "jupyter-lab --no-browser"

[dependencies]
python = "3.11.*"
jupyterlab = ">=4.2.3,<4.3"
pytorch = ">=2.3.1,<2.4"
torchvision = ">=0.18.1,<0.19"
biopython = ">=1.84,<2"
scipy = ">=1.14.0,<1.15"

```

### Issue description

```shell
PS C:\Users\Downloads\rosalind> pixi run start
✨ Pixi task (start in default): jupyter-lab --no-browser
  × An activation error occurred: IoError(Os { code: 5, kind: PermissionDenied, message: "액세스가
  │ 거부되었습니다." })

PS C:\Users\Downloads\rosalind> pixi run start
✨ Pixi task (start in default): jupyter-lab --no-browser
  × An activation error occurred: IoError(Os { code: 5, kind: PermissionDenied, message: "액세스가
  │ 거부되었습니다." })

PS C:\Users\Downloads\rosalind> pixi run start
✨ Pixi task (start in default): jupyter-lab --no-browser
  × failed to activate environment
  ╰─▶ An activation error occurred: IoError(Os { code: 5, kind: PermissionDenied, message: "액세스
      가 거부되었습니다." })

PS C:\Users\Downloads\rosalind> pixi run start
✨ Pixi task (start in default): jupyter-lab --no-browser
[I 2024-08-07 17:14:28.789 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-08-07 17:14:28.797 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-08-07 17:14:28.806 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-08-07 17:14:29.290 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-08-07 17:14:29.344 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-08-07 17:14:29.347 ServerApp] jupyter_lsp | extension was successfully loaded.
```

### Expected behavior

I'm encountering a peculiar issue with a script that runs flawlessly on Linux but throws a PermissionDenied error in the Windows PowerShell environment. What's even more perplexing is that the script occasionally executes successfully after multiple attempts.
The scenario is as follows:

The script runs without any issues on Linux.
When run in Windows PowerShell, it randomly results in a PermissionDenied error.
Surprisingly, repeated execution sometimes allows the script to run successfully.

This inconsistent behavior is quite confusing, and I'm struggling to understand the root cause. What could be the reason behind this erratic permission denial in PowerShell, especially considering its smooth operation in Linux?
Any insights or assistance in resolving this issue would be greatly appreciated. Thank you in advance for your help!

**Comment by ruben-arts** [comment]
The only thing that comes to mind directly would be, other tools or instances of pixi touching some files that this activation script is also running. Could you run the `pixi shell-hook` (outputs the activation script) and then see if there are any file called to activate the environment?

**Comment by partrita** [comment]
> The only thing that comes to mind directly would be, other tools or instances of pixi touching some files that this activation script is also running. Could you run the `pixi shell-hook` (outputs the activation script) and then see if there are any file called to activate the environment?

```bash
PS C:\Users\Downloads\rosalind> pixi shell-hook
$OutputEncoding = [System.Console]::OutputEncoding = [System.Console]::InputEncoding = [System.Text.Encoding]::UTF8
${Env:Path} = "C:\Users\Downloads\rosalind\.pixi\envs\default;C:\Users\Downloads\rosalind\.pixi\envs\default\Library/mingw-w64/bin;C:\Users\Downloads\rosalind\.pixi\envs\default\Library/usr/bin;C:\Users\Downloads\rosalind\.pixi\envs\default\Library/bin;C:\Users\Downloads\rosalind\.pixi\envs\default\Scripts;C:\Users\Downloads\rosalind\.pixi\envs\default\bin;C:\Program Files\PowerShell\7;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\GitHub CLI\;C:\Program Files\PowerShell\7\;C:\Users\scoop\apps\vscode\current\bin;C:\Users\.pixi\bin;C:\Users\scoop\shims;C:\Users\AppData\Local\Microsoft\WindowsApps;C:\Users\AppData\Local\Microsoft\WindowsApps"
${Env:CONDA_PREFIX} = "C:\Users\Downloads\rosalind\.pixi\envs\default"
${Env:PIXI_EXE} = "C:\Users\.pixi\bin\pixi.exe"
${Env:CONDA_DEFAULT_ENV} = "test_pixi"
${Env:PIXI_PROJECT_ROOT} = "C:\Users\Downloads\rosalind"
${Env:PIXI_PROJECT_MANIFEST} = "C:\Users\Downloads\rosalind\pixi.toml"
${Env:PIXI_ENVIRONMENT_NAME} = "default"
${Env:PIXI_IN_SHELL} = "1"
${Env:PIXI_PROJECT_NAME} = "test_pixi"
${Env:PIXI_PROJECT_VERSION} = "0.1.0"
${Env:PIXI_ENVIRONMENT_PLATFORMS} = "win-64"
${Env:PIXI_PROMPT} = "(test_pixi) "
. "C:\Users\Downloads\rosalind\.pixi\envs\default\etc/conda/activate.d\libxml2_activate.ps1"
. "C:\Users\Downloads\rosalind\.pixi\envs\default\etc/conda/activate.d\openssl_activate-win.ps1"
```

This is the output.

**Comment by apoorvkh** [comment]
I am also seeing a similar error on my Linux machine. Pixi was working fine, then I ran `pixi self-update --force` to update from 0.25.0 to 0.27.1.

Now, I get this error when I run `pixi shell` or `pixi shell-hook`

```
thread 'main' panicked at crates/pixi_utils/src/reqwest.rs:99:10:
failed to create reqwest Client: reqwest::Error { kind: Builder, source: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```


I'm not sure if `RUST_BACKTRACE=full pixi shell` is helpful:

```
thread 'main' panicked at crates/pixi_utils/src/reqwest.rs:99:10:
failed to create reqwest Client: reqwest::Error { kind: Builder, source: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }
stack backtrace:
   0:     0x7fd7f21e23e9 - <unknown>
   1:     0x7fd7f1638990 - <unknown>
   2:     0x7fd7f21a7a72 - <unknown>
   3:     0x7fd7f21e636e - <unknown>
   4:     0x7fd7f21e5be0 - <unknown>
   5:     0x7fd7f21e6c9b - <unknown>
   6:     0x7fd7f21e66c0 - <unknown>
   7:     0x7fd7f21e6616 - <unknown>
   8:     0x7fd7f21e6603 - <unknown>
   9:     0x7fd7f0f03144 - <unknown>
  10:     0x7fd7f0f036b2 - <unknown>
  11:     0x7fd7f1c0eeb2 - <unknown>
  12:     0x7fd7f0f32286 - <unknown>
  13:     0x7fd7f0f32189 - <unknown>
  14:     0x7fd7f12d6c62 - <unknown>
  15:     0x7fd7f11fba84 - <unknown>
  16:     0x7fd7f1259f44 - <unknown>
  17:     0x7fd7f12117d9 - <unknown>
  18:     0x7fd7f1545001 - <unknown>
  19:     0x7fd7f153fad9 - <unknown>
  20:     0x7fd7f1126573 - <unknown>
  21:     0x7fd7f1547fcb - <unknown
```

**Comment by apoorvkh** [comment]
Pixi version 0.26.1 works, but 0.27.0 doesn't.

**Comment by ruben-arts** [comment]
@apoorvkh I don't think this is the same issue, would you be able to make a new one and add your pixi toml to it aswell. Or find a minimal reproducing pixi.toml?

**Comment by ruben-arts** [comment]
@partrita Can you share the contents of: `C:\Users\Downloads\rosalind\.pixi\envs\default\etc/conda/activate.d\libxml2_activate.ps1` and `C:\Users\Downloads\rosalind\.pixi\envs\default\etc/conda/activate.d\openssl_activate-win.ps1`

And try to run these commands to see if they cause the issue.

**Comment by partrita** [comment]
I think I might have found a clue. The `pixi run` command works flawlessly in the Command Prompt (cmd), but it crashes when I try to use it in PowerShell.

```bash
$C:\Users\Downloads\rosalind\.pixi\envs\default\etc/conda/activate.d\libxml2_activate.ps1
C:\Users\Downloads\rosalind\.pixi\envs\default\etc/conda/activate.d\libxml2_activate.ps1: The term 'C:\Users\Downloads\rosalind\.pixi\envs\default\etc/conda/activate.d\libxml2_activate.ps1' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

```bash
$C:\Users\Downloads\rosalind\.pixi\envs\default\etc/conda/activate.d\openssl_activate-win.ps1
C:\Users\Downloads\rosalind\.pixi\envs\default\etc/conda/activate.d\openssl_activate-win.ps1: The term 'C:\Users\Downloads\rosalind\.pixi\envs\default\etc/conda/activate.d\openssl_activate-win.ps1' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by partrita** [comment]
> @partrita Can you share the contents of: `C:\Users\Downloads\rosalind\.pixi\envs\default\etc/conda/activate.d\libxml2_activate.ps1` and `C:\Users\Downloads\rosalind\.pixi\envs\default\etc/conda/activate.d\openssl_activate-win.ps1`
> 
> And try to run these commands to see if they cause the issue.

I think I might have found a clue. The `pixi run` command works flawlessly in the Command Prompt (cmd), but it crashes when I try to use it in PowerShell.

```bash
$C:\Users\Downloads\rosalind\.pixi\envs\default\etc/conda/activate.d\libxml2_activate.ps1
C:\Users\Downloads\rosalind\.pixi\envs\default\etc/conda/activate.d\libxml2_activate.ps1: The term 'C:\Users\Downloads\rosalind\.pixi\envs\default\etc/conda/activate.d\libxml2_activate.ps1' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

```bash
$C:\Users\Downloads\rosalind\.pixi\envs\default\etc/conda/activate.d\openssl_activate-win.ps1
C:\Users\Downloads\rosalind\.pixi\envs\default\etc/conda/activate.d\openssl_activate-win.ps1: The term 'C:\Users\Downloads\rosalind\.pixi\envs\default\etc/conda/activate.d\openssl_activate-win.ps1' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by ruben-arts** [comment]
It seems like we're not activating the right scripts. This is part of the activation workflow in pixi. 
I think we need to revisit which scripts are run by pixi on activation.

**Comment by baszalmstra** [comment]
I cannot reproduce this anymore. Closing. Please reopen if you still run into this!

**Comment by partrita** [comment]
> I cannot reproduce this anymore. Closing. Please reopen if you still run into this!

I guess, it fixed somehow.
