### ISSUE TITLE
Python GDAL Import Error in PyCharm after Micromamba and Pixi Installation

### ISSUE THREAD

**Issue by mht2953658596** [prefix-dev/pixi#1953]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell

```

Python GDAL Import Error in PyCharm after Micromamba and Pixi Installation

### Issue description

I've been using Python with Conda, but later installed Micromamba. Although Micromamba doesn't use the base environment, everything worked fine until I installed OpenCV in a Micromamba environment. During the installation, dependency conflicts occurred, and Micromamba started removing conflicting packages. However, when it tried to remove the GDAL package, it failed to delete the proj.db file, causing an error. I terminated the process and created a new environment in Micromamba to reinstall GDAL.

Now, I created a simple test script (test.py) with just one line:

```
`from osgeo import gdal`
Strangely, when I run the script directly from PyCharm, I get the following error:
Traceback (most recent call last):
  File "D:\code_space\shendong-gee\.pixi\envs\default\lib\site-packages\osgeo\__init__.py", line 30, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\code_space\shendong-gee\.pixi\envs\default\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "D:\code_space\shendong-gee\celery_worker\test.py", line 1, in <module>
    from osgeo import gdal
  File "D:\code_space\shendong-gee\.pixi\envs\default\lib\site-packages\osgeo\__init__.py", line 35, in <module>
    _gdal = swig_import_helper()
  File "D:\code_space\shendong-gee\.pixi\envs\default\lib\site-packages\osgeo\__init__.py", line 32, in swig_import_helper
    return importlib.import_module('_gdal')
  File "D:\code_space\shendong-gee\.pixi\envs\default\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal'
```
Additionally, when I try to import rasterio, I get this error:
Traceback (most recent call last):
  File "D:\code_space\shendong-gee\celery_worker\test.py", line 1, in <module>
    import rasterio
  File "D:\code_space\shendong-gee\.pixi\envs\default\lib\site-packages\rasterio\__init__.py", line 28, in <module>
    from rasterio._version import gdal_version, get_geos_version, get_proj_version
ImportError: DLL load failed while importing _version: The specified module could not be found.
```

I noticed that any libraries requiring DLLs seem to fail with a "specified module could not be found" error.

Thinking Micromamba might be the issue, I switched to Pixi, but the same problem persists. However, the strangest part is that when I run the script directly from the command line

D:\code_space\shendong-gee\.pixi\envs\default\python.EXE D:\code_space\shendong-gee\celery_worker\test.py

it works perfectly fine. The issue only occurs when running the script from PyCharm.

Does anyone have any idea what might be causing this, or how I could resolve the issue?

### Expected behavior

 When running the script from PyCharm, I expected it to execute without any errors, just as it does when running the script directly from the command line. Specifically, I expected:

The from osgeo import gdal line to execute successfully without any ImportError or ModuleNotFoundError.
The script to run without issues related to missing DLLs or modules.

**Comment by mht2953658596** [comment]
Finally, I uninstalled Conda, and then Pixi and Micromamba were able to correctly load the DLLs in PyCharm
