### ISSUE TITLE
Using `-` in pixi project name with `pixi init --format pyproject` will cause error on `pixi install`.

### ISSUE THREAD

**Issue by Robinlovelace** [prefix-dev/pixi#2066]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

I'm writing some slides advocating `pixi` as a cross-language environment builder, with the following content:

```bash
pixi init test-project --format pyproject
```

```
✔ Initialized project in ~/test-project
```

```bash
cd test-project
pixi add geopandas
pixi add --pypi --feature test pytest
pixi install
```

```
✔ Added pytest
Added these as pypi-dependencies.
Added these only for feature: test
```

Cross-language support (source: [pixi.sh](https://pixi.sh/latest/ide_integration/r_studio/))

```bash
pixi add r-ggplot2
```

### Issue description

Everything worked fine except for the last line, which generated:

```
pixi add r-ggplot2
 WARN The feature 'test' is defined but not used in any environment
  × default: error installing/updating PyPI dependencies
  ├─▶ Failed to prepare distributions
  ├─▶ Failed to fetch wheel: test-project @ file:///home/robin/github/robinlovelace/cross_language_projects/test-project
  ╰─▶ Build backend failed to build wheel through `build_editable()` with exit status: 1
      --- stdout:
      
      --- stderr:
      Traceback (most recent call last):
        File "<string>", line 11, in <module>
        File "/home/robin/.cache/rattler/cache/uv-cache/builds-v0/.tmpY4NrDC/lib/python3.12/site-packages/hatchling/build.py", line 83, in build_editable
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/robin/.cache/rattler/cache/uv-cache/builds-v0/.tmpY4NrDC/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 155, in
      build
          artifact = version_api[version](directory, **build_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/robin/.cache/rattler/cache/uv-cache/builds-v0/.tmpY4NrDC/lib/python3.12/site-packages/hatchling/builders/wheel.py", line 494, in build_editable
          return self.build_editable_detection(directory, **build_data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/robin/.cache/rattler/cache/uv-cache/builds-v0/.tmpY4NrDC/lib/python3.12/site-packages/hatchling/builders/wheel.py", line 505, in
      build_editable_detection
          for included_file in self.recurse_selected_project_files():
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/robin/.cache/rattler/cache/uv-cache/builds-v0/.tmpY4NrDC/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 180, in
      recurse_selected_project_files
          if self.config.only_include:
             ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/robin/.cache/rattler/cache/uv-cache/builds-v0/.tmpY4NrDC/lib/python3.12/site-packages/hatchling/builders/config.py", line 806, in only_include
          only_include = only_include_config.get('only-include', self.default_only_include()) or self.packages
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/robin/.cache/rattler/cache/uv-cache/builds-v0/.tmpY4NrDC/lib/python3.12/site-packages/hatchling/builders/wheel.py", line 260, in
      default_only_include
          return self.default_file_selection_options.only_include
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/robin/github/robinlovelace/cross_language_projects/test-project/.pixi/envs/default/lib/python3.12/functools.py", line 993, in __get__
          val = self.func(instance)
                ^^^^^^^^^^^^^^^^^^^
        File "/home/robin/.cache/rattler/cache/uv-cache/builds-v0/.tmpY4NrDC/lib/python3.12/site-packages/hatchling/builders/wheel.py", line 248, in
      default_file_selection_options
          raise ValueError(message)
      ValueError: Unable to determine which files to ship inside the wheel using the following heuristics: https://hatch.pypa.io/latest/plugins/builder/wheel/
      #default-file-selection
      
      The most likely cause of this is that there is no directory that matches the name of your project (test_project).
      
      At least one file selection option must be defined in the `tool.hatch.build.targets.wheel` table, see: https://hatch.pypa.io/latest/config/build/
      
      As an example, if you intend to ship a directory named `foo` that resides within a `src` directory located at the root of your project, you can define the
      following:
      
      [tool.hatch.build.targets.wheel]
      packages = ["src/foo"]
      ---
```

### Expected behavior

An easier-to-interpret error message or no error and the R package installs without issue

**Comment by Robinlovelace** [comment]
```
pixi --version
pixi 0.29.0
```

**Comment by ruben-arts** [comment]
Thanks for the issue. This however has to do with our `init` not acting nice:
```
pixi init test-project --format pyproject
cd test-project
pixi install
```
Which gives the error you're getting.

**Comment by ruben-arts** [comment]
Lol I found the culprit. The fact that a `-` was used in the project name was not accepted by `hatchling` as a project name cant have `-`s. It works with:

```
pixi init test_project --format pyproject
cd test_project
pixi install
```

Going to work on a fix.

**Comment by Robinlovelace** [comment]
Thanks and great job on finding the cause. In meantime I'll work-around by avoiding the pesky "-".

**Comment by Robinlovelace** [comment]
Will the fix work just by re-installing pixi using standard install script?

**Comment by ruben-arts** [comment]
We'll first have to make a release, will test some more and do the release tomorrow. If you're really eager you can install pixi from source.
