### ISSUE TITLE
Build backend failed to build wheel of pyproject when there is a hyphen (-) in project name of pixi init

### ISSUE THREAD

**Issue by j-horak** [prefix-dev/pixi#2105]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi init --format pyproject pixi-error
cd pixi-error
pixi add numpy
```

This is the produced `pyproject.toml`
```{toml}
[project]
authors = [{name = "Jacob Horak", email = "jacob.horak@mpsd.mpg.de"}]
dependencies = []
description = "Add a short description here"
name = "pixi-error"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
pixi-error = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
numpy = ">=2.1.1,<3"
```

### Issue description

When I create a python package project that contains a hyphen with `pixi init --format pyproject pixi-error` the sub dir `src/pixi-error` is created. This leads then to an error when trying to build the project which is triggered, e.g., via `pixi add numpy`.

The output is then

```bash
× default: error installing/updating PyPI dependencies
  ├─▶ Failed to prepare distributions
  ├─▶ Failed to fetch wheel: pixi-error @ file:///home/jhorak/Documents/gitlab-jacobhorak/pixi-error
  ╰─▶ Build backend failed to build wheel through `build_editable()` with exit status: 1
      --- stdout:
      
      --- stderr:
      Traceback (most recent call last):
        File "<string>", line 11, in <module>
        File "/home/jhorak/.cache/rattler/cache/uv-cache/builds-v0/.tmpzbnkw7/lib/python3.12/site-packages/hatchling/build.py", line 83, in build_editable
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['editable'])))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/jhorak/.cache/rattler/cache/uv-cache/builds-v0/.tmpzbnkw7/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 155, in build
          artifact = version_api[version](directory, **build_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/jhorak/.cache/rattler/cache/uv-cache/builds-v0/.tmpzbnkw7/lib/python3.12/site-packages/hatchling/builders/wheel.py", line 494, in build_editable
          return self.build_editable_detection(directory, **build_data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/jhorak/.cache/rattler/cache/uv-cache/builds-v0/.tmpzbnkw7/lib/python3.12/site-packages/hatchling/builders/wheel.py", line 505, in build_editable_detection
          for included_file in self.recurse_selected_project_files():
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/jhorak/.cache/rattler/cache/uv-cache/builds-v0/.tmpzbnkw7/lib/python3.12/site-packages/hatchling/builders/plugin/interface.py", line 180, in recurse_selected_project_files
          if self.config.only_include:
             ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/jhorak/.cache/rattler/cache/uv-cache/builds-v0/.tmpzbnkw7/lib/python3.12/site-packages/hatchling/builders/config.py", line 806, in only_include
          only_include = only_include_config.get('only-include', self.default_only_include()) or self.packages
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/jhorak/.cache/rattler/cache/uv-cache/builds-v0/.tmpzbnkw7/lib/python3.12/site-packages/hatchling/builders/wheel.py", line 260, in default_only_include
          return self.default_file_selection_options.only_include
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/jhorak/Documents/gitlab-jacobhorak/pixi-error/.pixi/envs/default/lib/python3.12/functools.py", line 993, in __get__
          val = self.func(instance)
                ^^^^^^^^^^^^^^^^^^^
        File "/home/jhorak/.cache/rattler/cache/uv-cache/builds-v0/.tmpzbnkw7/lib/python3.12/site-packages/hatchling/builders/wheel.py", line 248, in default_file_selection_options
          raise ValueError(message)
      ValueError: Unable to determine which files to ship inside the wheel using the following heuristics: https://hatch.pypa.io/latest/plugins/builder/wheel/#default-file-selection
      
      The most likely cause of this is that there is no directory that matches the name of your project (pixi_error).
      
      At least one file selection option must be defined in the `tool.hatch.build.targets.wheel` table, see: https://hatch.pypa.io/latest/config/build/
      
      As an example, if you intend to ship a directory named `foo` that resides within a `src` directory located at the root of your project, you can define the following:
      
      [tool.hatch.build.targets.wheel]
      packages = ["src/foo"]
      ---
```

### Expected behavior

When creating the project the dir should look like `src/pixi_error`.

This is what `uv init --lib uv-noerror` does. It yields a `src/uv_noerror` where I can install packages with `uv add`.

**Comment by olivier-lacroix** [comment]
I believe this has been fixed in the latest version. Are you running pixi 0.30 ?
