### ISSUE TITLE
InvalidVersionSpec(InvalidConstraint(ExpectedEof)) when trying to install RAPIDS

### ISSUE THREAD

**Issue by jacobtomlinson** [prefix-dev/pixi#278]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
$ curl -fsSL https://pixi.sh/install.sh | bash
$ pixi init pixi-rapids-test --channel rapidsai --channel conda-forge --channel nvidia
$ cd pixi-rapids-test
$ export RUST_BACKTRACE=full  # to get better error for GitHub issue
$ pixi add rapids==23.08 python==3.10 cudatoolkit==11.8 ipython
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidVersionSpec(InvalidConstraint(ExpectedEof))', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rattler_libsolv_rs-0.7.0/src/pool.rs:213:61
stack backtrace:
   0:     0x7f4bdd298e5a - std::backtrace_rs::backtrace::libunwind::trace::hfdbe65a70cbe5124
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f4bdd298e5a - std::backtrace_rs::backtrace::trace_unsynchronized::he2d1535323c42931
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f4bdd298e5a - std::sys_common::backtrace::_print_fmt::hab149acdfa5c515a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f4bdd298e5a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he12b586f68e91b77
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f4bdd2e17ff - core::fmt::write::hc9b09f10c793ddf8
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:     0x7f4bdd293f35 - std::io::Write::write_fmt::h2c6ee5e4a01225f0
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6:     0x7f4bdd298c25 - std::sys_common::backtrace::_print::hb125dc438dd5f408
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f4bdd298c25 - std::sys_common::backtrace::print::h75b2579ae28505d3
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f4bdd29a46e - std::panicking::default_hook::{{closure}}::h6770bc0e6b92c297
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9:     0x7f4bdd29a215 - std::panicking::default_hook::h10d80c7c91e6d7f6
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10:     0x7f4bdd29a9ce - std::panicking::rust_panic_with_hook::hef54f15d36ba505a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
  11:     0x7f4bdd29a8c9 - std::panicking::begin_panic_handler::{{closure}}::h68f165a2c696be7f
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
  12:     0x7f4bdd2992c6 - std::sys_common::backtrace::__rust_end_short_backtrace::h40e1d7ae5c92331e
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x7f4bdd29a622 - rust_begin_unwind
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  14:     0x7f4bdc6af343 - core::panicking::panic_fmt::hbf443f24a3a55022
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  15:     0x7f4bdc6af7f3 - core::result::unwrap_failed::hdaa067f32f4c1fb6
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
  16:     0x7f4bdca95ea9 - rattler_libsolv_rs::pool::Pool::intern_matchspec::h4b01172604a2f867
  17:     0x7f4bdca954b1 - rattler_libsolv_rs::pool::Pool::add_dependency::hfdd75dc8fc806896
  18:     0x7f4bdc881807 - rattler_solve::libsolv_rs::input::add_repodata_records::he6179cd0a19f4432
  19:     0x7f4bdc8d6e77 - <rattler_solve::libsolv_rs::Solver as rattler_solve::SolverImpl>::solve::h182759ffc76efc23
  20:     0x7f4bdc90971e - pixi::cli::add::determine_best_version::h476a7b2df5033708
  21:     0x7f4bdc81ec93 - pixi::cli::execute_command::{{closure}}::h5c657c8d6c5b041a
  22:     0x7f4bdc831964 - tokio::runtime::park::CachedParkThread::block_on::h583ab4e2e34cebf8
  23:     0x7f4bdc70bbab - tokio::runtime::context::runtime::enter_runtime::h198b3127395def33
  24:     0x7f4bdc70c41e - tokio::runtime::runtime::Runtime::block_on::h9d8887420419d292
  25:     0x7f4bdc8593b6 - pixi::main::ha06e3ba098ef79cc
  26:     0x7f4bdc7e8b63 - std::sys_common::backtrace::__rust_begin_short_backtrace::h57ab3d3f44d1bbfc
  27:     0x7f4bdc7e8e19 - std::rt::lang_start::{{closure}}::h7ffd8d63177e4b7f
  28:     0x7f4bdd28c612 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h826ec84f4d22172a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
  29:     0x7f4bdd28c612 - std::panicking::try::do_call::h330f41e7cdb66fa2
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  30:     0x7f4bdd28c612 - std::panicking::try::h30d9a927415799ae
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  31:     0x7f4bdd28c612 - std::panic::catch_unwind::h0f7d81e60d1c7508
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  32:     0x7f4bdd28c612 - std::rt::lang_start_internal::{{closure}}::h91e177ac1f827128
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
  33:     0x7f4bdd28c612 - std::panicking::try::do_call::haf26aa5893f5930f
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  34:     0x7f4bdd28c612 - std::panicking::try::hd1a491374a98c81c
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  35:     0x7f4bdd28c612 - std::panic::catch_unwind::h9d9e54dec05b7526
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  36:     0x7f4bdd28c612 - std::rt::lang_start_internal::hebd4e8d348b0ef95
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
  37:     0x7f4bdc859495 - main
```

### Issue description

Thought I would have a quick go at installing RAPIDS using pixi and attempted to port [these conda instructions](https://rapids.ai/#quick-start) to pixi. However, when I try and add the packages I get a rust panic.

### Expected behavior

I would expect the packages to be added and then my goal was to try and run

```shell
$ pixi run ipython
```

**Comment by baszalmstra** [comment]
Thanks for the report! The issue was caused by the use of local versions (e.g. `...+<version>`) which wasn't expected in the repodata.

I fixed this issue in rattler: https://github.com/mamba-org/rattler/pull/281

Will be available with the next release most likely.

**Comment by wolfv** [comment]
Thanks @jacobtomlinson for reporting! One more edge-case gone thanks to community testing :)

**Comment by jacobtomlinson** [comment]
Thanks for the crazy fast turnaround!
